CREATE TABLE borrow(
    BORROW_ID bigint PRIMARY KEY,
    BUKU_ID bigint,
    MEMBER_ID bigint,
    BORROWED_AT DATETIME,
    DUE_AT DATETIME,
    LATE_FEE DOUBLE,
    FOREIGN KEY (BUKU_ID) REFERENCES buku(BUKU_ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (MEMBER_ID) REFERENCES member(MEMBER_ID) ON DELETE CASCADE ON UPDATE CASCADE
);